### ISSUE TITLE
getting privacy error while taking outh from facebook user

### ISSUE THREAD

**Issue by nehalindia** [AamAadmiParty/PostToFacebook#2]
![screenshot 7](https://user-images.githubusercontent.com/20025251/38072930-4ffa47c4-3346-11e8-9ea7-385f8685f538.png)
Step 1: When i hit the page on node server that shows login as
![screenshot 5](https://user-images.githubusercontent.com/20025251/38072839-e07bb69e-3345-11e8-9fbb-e0222752845e.png)
Step 2: when hit on continue as button that give privacy error because of that is not running on https.
Step 3: here is code of button:

`<div class="fb-login-button" data-width="200px" data-max-rows="2" data-size="large" data-button-type="continue_with" data-show-faces="true" 
data-auto-logout-link="false" data-use-continue-as="true" ng-serve="ssl"></div>`

**Comment by nehalkodigosoft** [comment]
This has been sorted.
